import assert from "node:assert/strict";
import { after, before, it } from "node:test";
import type { Server } from "node:http";
import { InMemoryAuthService } from "../src/domain/auth.js";
import { PortalService } from "../src/application/portal-service.js";
import { createHttpServer } from "../src/api/http-server.js";

let server: Server;
let baseUrl: string;

before(async () => {
  const auth = new InMemoryAuthService();
  const portal = new PortalService(auth);
  server = createHttpServer(auth, portal);
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  if (!address || typeof address === "string") throw new Error("テストサーバーのポートを取得できません。");
  baseUrl = `http://127.0.0.1:${address.port}`;
});

after(async () => {
  await new Promise<void>((resolve, reject) => server.close((error) => (error ? reject(error) : resolve())));
});

it("CMS-OS Portalの静的UIを配信する", async () => {
  const html = await fetch(`${baseUrl}/`);
  const body = await html.text();
  assert.equal(html.status, 200);
  assert.match(body, /CMS-OS Portal/);
  assert.match(body, /content-editor-panel/);
  assert.match(body, /content-edit-panel/);
  assert.match(body, /content-edit-form/);
  assert.match(body, /name="jsonLdType"/);
  assert.match(body, /name="faqJson"/);
  assert.match(body, /publication-history-list/);
  assert.match(body, /publication-schedule-panel/);
  assert.match(body, /publication-schedule-list/);
  assert.match(body, /site-seo-audit-button/);
  assert.match(body, /site-seo-audit-result/);
  assert.match(body, /content-version-list/);
  assert.match(body, /content-review-list/);
  assert.match(body, /provider-management-panel/);
  assert.match(body, /portal-planning-panel/);
  assert.match(body, /portal-planning-form/);
  assert.match(body, /portal-plan-result/);
  assert.match(body, /portal-plan-list/);
  assert.match(body, /job-management-panel/);
  assert.match(body, /media-management-panel/);
  assert.match(body, /media-management-form/);
  assert.match(body, /media-list/);
  assert.match(body, /request-inbox-panel/);
  assert.match(body, /application-panel/);
  assert.match(body, /inquiry-panel/);
  assert.match(body, /booking-panel/);
  assert.match(body, /booking-status-panel/);
  assert.match(body, /inquiry-management-panel/);
  assert.match(body, /notification-panel/);
  assert.match(body, /provider-theme-filter/);
  assert.match(body, /provider-theme-options/);
  assert.match(body, /provider-sort/);
  assert.match(body, /request-status-filter/);
  assert.match(body, /application-job-filter/);
  assert.match(body, /job-employment-filter/);
  assert.match(body, /job-sort/);
  assert.match(body, /provider-pagination/);
  assert.match(body, /provider-list-status/);
  assert.match(body, /directory-guide-panel/);
  assert.match(body, /directory-guide-list/);
  assert.match(body, /favorite-panel/);
  assert.match(body, /favorite-list/);
  assert.match(body, /provider-compare-panel/);
  assert.match(body, /provider-compare-list/);
  assert.match(body, /provider-profile-panel/);
  assert.match(body, /provider-profile-fields/);
  assert.match(body, /provider-profile-request/);
  assert.match(body, /provider-profile-booking/);
  assert.match(body, /provider-section-title/);
  assert.match(body, /provider-discovery/);
  assert.match(body, /experience-navigation/);
  assert.match(body, /directory-guide-title/);
  assert.match(body, /job-panel-title/);
  assert.match(body, /request-list-status/);
  assert.match(body, /application-list-status/);
  assert.match(body, /job-list-status/);
  assert.match(body, /request-pagination/);
  assert.match(body, /application-pagination/);
  assert.match(body, /job-pagination/);
  assert.match(body, /job-detail-panel/);
  assert.match(body, /job-detail-apply/);
  assert.match(body, /aria-live="polite"/);
  assert.match(body, /aria-busy="false"/);
  assert.match(body, /listing-submit-button/);
  assert.match(body, /login-form/);
  assert.match(body, /role-description/);
  assert.match(body, /mfa-panel/);
  assert.match(body, /value="recruiter"/);
  assert.match(body, /data-category="beauty" data-role="provider"/);
  assert.match(body, /data-category="labor-shortage" data-role="recruiter"/);

  const script = await fetch(`${baseUrl}/app.js`);
  assert.equal(script.status, 200);
  const scriptBody = await script.text();
  assert.match(scriptBody, /category-select/);
  assert.match(scriptBody, /api\/v1\/categories\/\$\{encodeURIComponent\(state\.category\)\}/);
  assert.match(scriptBody, /async function loadCategories/);
  assert.match(scriptBody, /api\("\/api\/v1\/categories"\)/);
  assert.match(scriptBody, /elements\.category\.replaceChildren/);
  assert.match(scriptBody, /availableContexts/);
  assert.match(scriptBody, /function renderRoleOptions/);
  assert.match(scriptBody, /selectedOptions/);
  assert.match(scriptBody, /dataset\.category/);
  assert.match(scriptBody, /function applyPrincipal/);
  assert.match(scriptBody, /moduleLabels/);
  assert.match(scriptBody, /navigationAnchorTargets/);
  assert.match(scriptBody, /resolveNavigationTarget/);
  assert.match(scriptBody, /elements\.navigation/);
  assert.match(scriptBody, /function isRecruiterRole/);
  assert.match(scriptBody, /navigationLabels\.themes/);
  assert.match(scriptBody, /providerThemeOptions/);
  assert.match(scriptBody, /themeOptions/);
  assert.match(scriptBody, /providerSectionTitle/);
  assert.match(scriptBody, /workflowTitle\.textContent = `\$\{primaryLabel\}/);
  assert.match(scriptBody, /visibleModules\.includes\("jobSearch"\)/);
  assert.match(scriptBody, /clearJobView/);
  assert.match(scriptBody, /api\/v1\/auth\/config/);
  assert.match(scriptBody, /api\/v1\/auth\/login-options/);
  assert.match(scriptBody, /function loadLoginOptions/);
  assert.match(scriptBody, /selectedRoleOption\?\.audience/);
  assert.match(scriptBody, /api\/v1\/auth\/context/);
  assert.match(scriptBody, /clearSessionState/);
  assert.match(scriptBody, /api\/v1\/auth\/oidc\/start/);
  assert.match(scriptBody, /api\/v1\/auth\/mfa\/complete/);
  assert.match(scriptBody, /api\/v1\/content\/proposals/);
  assert.match(scriptBody, /contentEditForm/);
  assert.match(scriptBody, /contentJsonLdTypes/);
  assert.match(scriptBody, /openContentEditor/);
  assert.match(scriptBody, /data-action="edit"/);
  assert.match(scriptBody, /method: "PATCH"/);
  assert.match(scriptBody, /api\/v1\/content\/.*translate/);
  assert.match(scriptBody, /api\/v1\/publications\/build/);
  assert.match(scriptBody, /api\/v1\/publications\/publish/);
  assert.match(scriptBody, /BuilderOS Adapterで公開/);
  assert.match(scriptBody, /api\/v1\/publications\/schedules/);
  assert.match(scriptBody, /publication-schedule-cancel-button/);
  assert.match(scriptBody, /reloadPublicationSchedules/);
  assert.match(scriptBody, /api\/v1\/publications\/unpublish/);
  assert.match(scriptBody, /api\/v1\/seo\/audit/);
  assert.match(scriptBody, /api\/v1\/publications/);
  assert.match(scriptBody, /publication-history/);
  assert.match(scriptBody, /handlePublicationRollback/);
  assert.match(scriptBody, /content-version-list/);
  assert.match(scriptBody, /handleContentVersionRestore/);
  assert.match(scriptBody, /request-review/);
  assert.match(scriptBody, /request-changes/);
  assert.match(scriptBody, /contentReviewStatusLabels/);
  assert.match(scriptBody, /api\/v1\/providers\//);
  assert.match(scriptBody, /api\/v1\/jobs/);
  assert.match(scriptBody, /async function openJobDetail/);
  assert.match(scriptBody, /job-detail-button/);
  assert.match(scriptBody, /api\(`\/api\/v1\/jobs\/\$\{encodeURIComponent\(jobId\)\}`\)/);
  assert.match(scriptBody, /job-status-button/);
  assert.match(scriptBody, /api\/v1\/requests/);
  assert.match(scriptBody, /api\/v1\/applications/);
  assert.match(scriptBody, /api\/v1\/inquiries/);
  assert.match(scriptBody, /api\/v1\/notifications/);
  assert.match(scriptBody, /api\/v1\/favorites/);
  assert.match(scriptBody, /favorite-provider-button/);
  assert.match(scriptBody, /function reloadFavorites/);
  assert.match(scriptBody, /provider-compare-button/);
  assert.match(scriptBody, /api\/v1\/providers\/compare/);
  assert.match(scriptBody, /function loadProviderComparison/);
  assert.match(scriptBody, /provider-profile-button/);
  assert.match(scriptBody, /async function openProviderProfile/);
  assert.match(scriptBody, /function focusRequestForm/);
  assert.match(scriptBody, /providerProfileRequest/);
  assert.match(scriptBody, /api\(`\/api\/v1\/providers\/\$\{encodeURIComponent\(providerId\)\}`\)/);
  assert.match(scriptBody, /function renderProviderProfile/);
  assert.match(scriptBody, /buildListQuery/);
  assert.match(scriptBody, /reloadProviders/);
  assert.match(scriptBody, /reloadJobs/);
  assert.match(scriptBody, /jobPanel: document\.querySelector\("#job-panel"\)/);
  assert.match(scriptBody, /reloadRequests/);
  assert.match(scriptBody, /reloadBookings/);
  assert.match(scriptBody, /reloadApplications/);
  assert.match(scriptBody, /api\/v1\/bookings/);
  assert.match(scriptBody, /booking-status-button/);
  assert.match(scriptBody, /renderListPagination/);
  assert.match(scriptBody, /nextCursor/);
  assert.match(scriptBody, /listRequestVersions/);
  assert.match(scriptBody, /window\.clearTimeout/);
  assert.match(scriptBody, /focus\(\)/);
  assert.match(scriptBody, /setListStatus/);
  assert.match(scriptBody, /再試行/);
  assert.match(scriptBody, /api\/v1\/categories\/\$\{encodeURIComponent\(state\.category\)\}\/directories/);
  assert.match(scriptBody, /directoryGuideKindLabels/);
  assert.match(scriptBody, /listing-submission/);
  assert.match(scriptBody, /api\/v1\/portal-plans/);
  assert.match(scriptBody, /portal\.plan\.create/);
  assert.match(scriptBody, /portal-plan-draft-button/);
  assert.match(scriptBody, /api\/v1\/portal-plans\/\$\{encodeURIComponent\(button\.dataset\.planId \?\? \"\"\)\}\/draft/);
  assert.match(scriptBody, /reloadPortalPlanning/);
  assert.match(scriptBody, /matchingContentCount/);
  assert.match(scriptBody, /role-status-button/);
  assert.match(scriptBody, /api\/v1\/media/);
  assert.match(scriptBody, /reloadMediaManagement/);
  assert.match(scriptBody, /media-transform-button/);
  assert.match(body, /media-seo-audit-button/);
  assert.match(body, /media-seo-audit-result/);
  assert.match(scriptBody, /api\/v1\/media\/seo-audit/);
  assert.match(scriptBody, /runMediaSeoAudit/);
});
